### ISSUE TITLE
 how to use it in conjunction with ORM frameworks?

### ISSUE THREAD

**Issue by Naylor55** [sebasbaumh/postgis-java-ng#205]
I carefully read the contents of the README.md file and pulled the code repository to my work computer to roughly browse the source code. My question now is how to use it in conjunction with ORM frameworks?

In actual projects, SpringBoot+MybatisPlus is used, where MybatisPlus serves as the ORM framework to map database types and Java application types. During CURD, types can be automatically mapped through TypeHandler, and developers do not need to worry about type mapping.

**Comment by sebasbaumh** [comment]
There is no explicit support for MybatisPlus, but usually you can register the types using the [`io.github.sebasbaumh.postgis.DriverWrapper#registerDataTypes`](https://github.com/sebasbaumh/postgis-java-ng/blob/master/src/main/java/io/github/sebasbaumh/postgis/DriverWrapper.java) on your Connection and then use them.

**Comment by Naylor55** [comment]
thanks!  I will try it out
